name: CI
on:
  push:
    branches:
      - master
    workflow_dispatch: # allow manual triggering

jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            name/app
          tags: |
            {{sha}}

      - name: Login to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ steps.meta.outputs.tags }}
          secrets: |
            DOCKER_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo 'TELEGRAM_BOT_TOKEN="${{ secrets.ENV_TELEGRAM_BOT_TOKEN }}"' > .env
          echo 'OPENAI_API_KEY="${{ secrets.ENV_OPENAI_API_KEY }}"' >> .env
          echo 'ALLOWED_USER_IDS="${{ secrets.ENV_ALLOWED_USER_IDS }}"' >> .env

      - name: Install dependencies
        run: yarn install

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ steps.meta.outputs.tags }}

      - name: Confirm SSH host key
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> known_hosts
          ssh-keygen -lf known_hosts

      - name: Deploy app to server
        uses: invi5H/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ steps.meta.outputs.tags }}
            docker stop gpt-translator-bot || true
            docker rm gpt-translator-bot || true
            docker run -d --name gpt-translator-bot ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ steps.meta.outputs.tags }}
          ssh_known_hosts: ${{ secrets.SERVER_IP }}, ${{ secrets.SERVER_HOSTKEY }}}
