name: Deploy to server

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  ENV_TELEGRAM_BOT_TOKEN: ${{ secrets.ENV_TELEGRAM_BOT_TOKEN }}
  ENV_OPENAI_API_KEY: ${{ secrets.ENV_OPENAI_API_KEY }}
  ENV_ALLOWED_USER_IDS: ${{ secrets.ENV_ALLOWED_USER_IDS }}
  IMAGE_TAG: ${{ secrets.DOCKER_USERNAME }}/gpt-translator-bot:latest
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: /ssh/known_hosts

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          port: 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop gpt-translator-bot || true
            docker rm gpt-translator-bot || true
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            docker pull ${{ env.IMAGE_TAG }}
            docker build . -t ${{ env.IMAGE_TAG }}
            docker run -d --restart always --name gpt-translator-bot -e TELEGRAM_BOT_TOKEN=${{ secrets.ENV_TELEGRAM_BOT_TOKEN }} -e OPENAI_API_KEY=${{ secrets.ENV_OPENAI_API_KEY }} -e ALLOWED_USER_IDS=${{ secrets.ENV_ALLOWED_USER_IDS }} ${{ env.IMAGE_TAG }}
