name: Build and deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      IMAGE_TAG: gpt-translator-bot:${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo 'TELEGRAM_BOT_TOKEN="${{ secrets.ENV_TELEGRAM_BOT_TOKEN }}"' > .env
          echo 'OPENAI_API_KEY="${{ secrets.ENV_OPENAI_API_KEY }}"' >> .env
          echo 'ALLOWED_USER_IDS="${{ secrets.ENV_ALLOWED_USER_IDS }}"' >> .env

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY }}
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        secrets:
          DOCKER_USERNAME: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_TAG }}
          build-args: |
            NODE_ENV=production

      - name: Deploy to server
        uses: invi5H/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_TAG }}
            docker run -d ${{ secrets.DOCKER_REGISTRY }}/${{ env.IMAGE_TAG }}
