name: CI
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn install

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          no-cache: true
          platforms: linux/amd64
          tags: '***/gpt-translator-bot:${{ github.sha }}'
          secrets: |
            DOCKER_USERNAME=${{ secrets.DOCKER_REGISTRY_USERNAME }}
            DOCKER_PASSWORD=${{ secrets.DOCKER_REGISTRY_PASSWORD }}

  deploy:
    name: Deploy to production server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo 'TELEGRAM_BOT_TOKEN="${{ secrets.ENV_TELEGRAM_BOT_TOKEN }}"' > .env
          echo 'OPENAI_API_KEY="${{ secrets.ENV_OPENAI_API_KEY }}"' >> .env
          echo 'ALLOWED_USER_IDS="${{ secrets.ENV_ALLOWED_USER_IDS }}"' >> .env

      - name: Install dependencies
        run: yarn install

      - name: Pull Docker image
        run: docker pull ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ github.sha }}

      - name: Confirm SSH host key
        run: |
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> known_hosts
          ssh-keygen -lf known_hosts

      - name: Deploy app to server
        uses: appleboy/ssh-action
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ github.sha }}
            docker stop gpt-translator-bot || true
            docker rm gpt-translator-bot || true
            docker run -d --name gpt-translator-bot ${{ secrets.DOCKER_REGISTRY }}/gpt-translator-bot:${{ github.sha }}
          ssh_known_hosts: ${{ secrets.SERVER_IP }}, ${{ secrets.SERVER_HOSTKEY }}
